[2023-03-10 04:05:15,439] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,440] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,440] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,486] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,440] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,489] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,489] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:05:15,439] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,492] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,492] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:05:15,439] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,497] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,439] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,497] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,497] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:05:15,497] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:05:15,496] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,496] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,488] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:05:15,505] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,505] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,479] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,478] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,513] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:05:15,510] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,509] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,509] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,505] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,516] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,516] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,517] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,515] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,517] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,515] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,517] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,515] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:05:15,518] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,518] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,518] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,520] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,520] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,520] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,540] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,542] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,542] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:05:15,548] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,548] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,548] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,620] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,620] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,620] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,620] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,627] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,627] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,621] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:15,808] WARN [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:05:15,809] WARN [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:05:15,809] WARN [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:05:15,833] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,833] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,809] WARN [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:05:15,832] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,833] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,832] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,833] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:15,833] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:05:15,834] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:05:19,763] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:20,052] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:20,053] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:20,053] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:05:20,053] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,430] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,431] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,431] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:20:51,431] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,485] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,485] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:20:51,431] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,493] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,493] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:20:51,431] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,499] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,499] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:20:51,431] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,505] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,505] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:20:51,430] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,508] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,432] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,508] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:20:51,509] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,509] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,510] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:20:51,510] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,511] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,515] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,515] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,517] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,517] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,514] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,517] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,517] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,515] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,517] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,532] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,533] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,533] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:20:51,542] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,543] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,543] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,618] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,618] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,618] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,618] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,618] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,618] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,618] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:51,650] WARN [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:20:51,650] WARN [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:20:51,650] WARN [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:20:51,657] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,657] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,656] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,652] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,658] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,651] WARN [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:20:51,658] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:51,659] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:20:51,659] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:20:53,061] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:53,068] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:53,070] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:53,071] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:20:53,076] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:21:05,592] INFO [test_snowflake_connector|task-0] 
[SF_KAFKA_CONNECTOR] list stage SNOWFLAKE_KAFKA_CONNECTOR_test_snowflake_connector_STAGE_test_table retrieved 1 file names (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:79)
[2023-03-10 04:21:05,596] WARN [test_snowflake_connector|task-0] Resetting cleaner files SNOWFLAKE_KAFKA_CONNECTOR_test_snowflake_connector_PIPE_test_table_0 done (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1:103)
[2023-03-10 04:36:41,441] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,445] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,445] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,447] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,446] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,489] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,446] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,491] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,446] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,492] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:36:41,446] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,493] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,493] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:36:41,446] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,493] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:36:41,492] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:36:41,492] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:36:41,489] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,495] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:36:41,488] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,495] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:36:41,514] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:41,517] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:41,516] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,520] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:41,520] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,520] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,520] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,520] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,519] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,521] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,518] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,521] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,520] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,521] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,609] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:36:41,609] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:36:41,609] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:36:42,917] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:42,931] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:42,931] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:42,931] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:42,934] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:42,935] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:42,934] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:42,935] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:36:43,673] ERROR [test_snowflake_connector|task-0] Operation timed out (Read failed) (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,482] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,483] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,483] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,483] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,483] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:52:26,483] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:52:26,482] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:52:26,482] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:52:26,482] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,501] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:52:26,441] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,504] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:52:26,498] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,507] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,507] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,498] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,498] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,498] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,483] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:52:26,509] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,509] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,509] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,509] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,511] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,508] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,505] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,512] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,512] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,511] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,511] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,512] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,512] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,512] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,512] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,627] INFO [test_snowflake_connector|task-7] [Consumer clientId=connector-consumer-test_snowflake_connector-7, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,633] INFO [test_snowflake_connector|task-4] [Consumer clientId=connector-consumer-test_snowflake_connector-4, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,635] INFO [test_snowflake_connector|task-5] [Consumer clientId=connector-consumer-test_snowflake_connector-5, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,637] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,636] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,639] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,639] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,638] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:26,825] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,825] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Client requested disconnect from node 2147483647 (org.apache.kafka.clients.NetworkClient:324)
[2023-03-10 04:52:26,833] WARN [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:52:26,834] WARN [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:52:26,833] WARN [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:52:26,833] WARN [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Error connecting to node 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient:997)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:482)
	at sun.nio.ch.Net.connect(Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:647)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:590)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:897)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:873)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:617)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:427)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:497)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:529)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1272)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:475)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:331)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2023-03-10 04:52:26,838] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,838] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,837] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,838] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,837] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,838] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,836] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:959)
[2023-03-10 04:52:26,838] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Requesting disconnect from last known coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:972)
[2023-03-10 04:52:26,868] ERROR [test_snowflake_connector|task-0] vn94816.us-east-2.aws.snowflakecomputing.com: nodename nor servname provided, or not known (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-10 04:52:28,132] INFO [test_snowflake_connector|task-0] [Consumer clientId=connector-consumer-test_snowflake_connector-0, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:28,264] INFO [test_snowflake_connector|task-3] [Consumer clientId=connector-consumer-test_snowflake_connector-3, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:28,272] INFO [test_snowflake_connector|task-2] [Consumer clientId=connector-consumer-test_snowflake_connector-2, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:28,275] INFO [test_snowflake_connector|task-1] [Consumer clientId=connector-consumer-test_snowflake_connector-1, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:28,275] INFO [test_snowflake_connector|task-6] [Consumer clientId=connector-consumer-test_snowflake_connector-6, groupId=connect-test_snowflake_connector] Discovered group coordinator 192.168.113.228:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:896)
[2023-03-10 04:52:28,884] ERROR [test_snowflake_connector|task-0] vn94816.us-east-2.aws.snowflakecomputing.com (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-10 04:52:32,898] ERROR [test_snowflake_connector|task-0] vn94816.us-east-2.aws.snowflakecomputing.com (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-10 04:52:43,355] ERROR [test_snowflake_connector|task-0] HTTP Status: 401 ErrorBody: {
  "data" : null,
  "code" : "390144",
  "message" : "JWT token is invalid.",
  "success" : false,
  "headers" : null
} (com.snowflake.kafka.connector.internal.InternalUtils:284)
[2023-03-10 04:52:43,356] WARN [test_snowflake_connector|task-0] Cleaner encountered an exception class com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:

[SF_KAFKA_CONNECTOR] Exception: Failed to read load history
[SF_KAFKA_CONNECTOR] Error Code: 3002
[SF_KAFKA_CONNECTOR] Detail: Exception reported by Ingest SDK
[SF_KAFKA_CONNECTOR] Message: 
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Exception: Max retry exceeded
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Error Code: 2010
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Detail: Api retry exceeded the max retry limit
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] Message: HTTP Status: 401 ErrorBody: {
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "data" : null,
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "code" : "390144",
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "message" : "JWT token is invalid.",
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "success" : false,
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR]   "headers" : null
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] }
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] net.snowflake.ingest.connection.ServiceResponseHandler.handleExceptionalStatus(ServiceResponseHandler.java:199)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] net.snowflake.ingest.connection.ServiceResponseHandler.unmarshallHistoryResponse(ServiceResponseHandler.java:127)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] net.snowflake.ingest.SimpleIngestManager.getHistory(SimpleIngestManager.java:528)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.lambda$readIngestReport$2(SnowflakeIngestionServiceV1.java:122)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.InternalUtils.backoffAndRetry(InternalUtils.java:279)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.readIngestReport(SnowflakeIngestionServiceV1.java:121)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:709)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:415)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SF_KAFKA_CONNECTOR] [SF_KAFKA_CONNECTOR] java.lang.Thread.run(Thread.java:748)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:427)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:403)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:390)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.InternalUtils.backoffAndRetry(InternalUtils.java:288)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.readIngestReport(SnowflakeIngestionServiceV1.java:121)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:709)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:415)
[SF_KAFKA_CONNECTOR] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[SF_KAFKA_CONNECTOR] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SF_KAFKA_CONNECTOR] java.lang.Thread.run(Thread.java:748)
[com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:427), com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:403), com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:390), com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1.readIngestReport(SnowflakeIngestionServiceV1.java:126), com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:709), com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:415), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)] (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1:103)
